channels:
- conda-forge
dependencies:
- python=3.10.19
- pip<=25.3
- pip:
  - mlflow==3.7.0
  - joblib>=1.3
  - matplotlib>=3.8
  - seaborn>=0.13.2
  - numpy>=1.26
  - pandas>=2.2.3
  - scikit-learn>=1.4
  - yellowbrick>=1.5
name: mlflow-env



