name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==3.7.0
      - scikit-learn
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - yellowbrick
